language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -U pip
  - pip install codecov
  - pip install -r requirements_dev.txt

before_script:
  - pip freeze

script:
  - py.test --cov choose
  - flake8 .

after_success:
  - codecov
